### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by DeadEnded** [custom-components/weatheralerts#17]
**Version of the cusom_component**
9acd01b

**Describe the bug**
On startup HA log gives list index out of range.

**log**

```
Log Details (ERROR)
Wed Jul 24 2019 00:08:41 GMT-0400 (Eastern Daylight Time)
list index out of range
```

I have just installed this from HACS.
I did see that another user had this error and changed their sameid and got it working.
Could there be a problem where some sameid's do not work?

Here is the snip of my configuration.yaml:

```
sensor:

  # NWS NOAA Alerts
  - platform: weatheralerts
    sameid: '021209'
```

Thank you!
DeadEnd
