### ISSUE TITLE
error without further content

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-components/weatheralerts#27]
**Version of the custom_component**

**Describe the bug**
Not sure, but the sensor is not created and an empty error is displayed in the log

config is:
HA Hassio, Rpi4 103.5
```
sensor:
# https://github.com/custom-components/weatheralerts
# New Orleans, Louisiana
  - platform: weatheralerts
    state: LA
    zone: 62
```

tried it with` '062'` also, same error

**Log**

```
Add your logs here.
```
![Schermafbeelding 2020-01-02 om 11 35 47](https://user-images.githubusercontent.com/33354141/71663069-102b5700-2d54-11ea-866f-18e71b30be5c.jpg)
![Schermafbeelding 2020-01-02 om 11 35 53](https://user-images.githubusercontent.com/33354141/71663070-102b5700-2d54-11ea-8f8a-c29ed3f8258b.jpg)
