### ISSUE TITLE
no sensor being created

### ISSUE THREAD

**Issue by ReenigneArcher** [custom-components/weatheralerts#78]
**Version of the custom_component**

v0.1.5

**Describe the bug**
No sensor is being created. Also no entries in the logs...

configuration.yaml:
```yml
sensor: !include_dir_merge_list include_files/sensor/
```

include_files/sensor/weatheralerts.yaml:
```yml
platform: weatheralerts
state: WI
zone: 38
county: 87
```

also tried (which seems more correct to me):
```yml
- platform: weatheralerts
  state: WI
  zone: 38
  county: 87
```

**Log**

```
Nothing appears in logs...
```
